export const actionTypes = {
  START_IMAGE_UPLOAD: 'profile/START_IMAGE_UPLOAD',
  SUCCESS_IMAGE_UPLOAD: 'profile/SUCCESS_IMAGE_UPLOAD',
  FAILED_IMAGE_UPLOAD: 'profile/FAILED_IMAGE_UPLOAD',

  START_GETTING_DEFAULT_IMAGES: 'profile/START_GETTING_DEFAULT_IMAGES',
  SUCCESS_GETTING_DEFAULT_IMAGES: 'profile/SUCCESS_GETTING_DEFAULT_IMAGES',
  FAILED_GETTING_DEFAULT_IMAGES: 'profile/FAILED_GETTING_DEFAULT_IMAGES',

  START_ADDING_DEFAULT_PIC: 'profile/START_ADDING_DEFAULT_PIC',
  SUCCESS_ADDING_DEFAULT_PIC: 'profile/SUCCESS_ADDING_DEFAULT_PIC',
  FAILED_ADDING_DEFAULT_PIC: 'profile/FAILED_ADDING_DEFAULT_PIC',

  START_GETTING_USER_POSTS: 'profile/START_GETTING_USER_POSTS',
  SUCCESS_GETTING_USER_POSTS: 'profile/SUCCESS_GETTING_USER_POSTS',
  FAILED_GETTING_USERS_POST: 'profile/FAILED_GETTING_USERS_POST',
}
