export const actionTypes = {
  START_GETTING_OG_DATA: 'ogData/START_GETTING_OG_DATA',
  SUCCESS_GETTING_OG_DATA: 'ogData/SUCCESS_GETTING_OG_DATA',
  FAILED_GETTING_OG_DATA: 'ogData/FAILED_GETTING_OG_DATA',
}
