export const actionTypes = {
  START_GOOGLE_LOGIN: 'login/START_GOOGLE_LOGIN',
  SUCCESS_GOOGLE_LOGIN: 'login/SUCCESS_GOOGLE_LOGIN',
  FAILED_GOOGLE_LOGIN: 'login/FAILED_GOOGLE_LOGIN',
  SET_LOG_IN_STATE: 'login/SET_LOG_IN_STATE',
}
