export const actionTypes = {
  START_GETTING_USER_DATA: 'user/START_GETTING_USER_DATA',
  SUCCESS_GETTING_USER_DATA: 'user/SUCCESS_GETTING_USER_DATA',
  FAILED_GETTING_USER_DATA: 'user/FAILED_GETTING_USER_DATA',
  UPDATE_USER_DATA: 'user/UPDATE_USER_DATA',
}
