export const actionTypes = {
  TOGGLE_ADD_LINK_DRAWER: 'home/TOGGLE_ADD_LINK_DRAWER',

  START_ADD_POST: 'home/START_ADD_POST',
  SUCCESS_ADD_POST: 'home/SUCCESS_ADD_POST',
  FAILED_ADD_POST: 'home/FAILED_ADD_POST',

  UPDATE_POSTS: 'home/UPDATE_POSTS',

  SET_POSTS_FILTER: 'home/SET_POSTS_FILTER',
}
